spring.application.name=MajorDNA AI
server.port=8080
spring.jackson.serialization.indent-output=true
server.error.include-message=always
majordna.llm.enabled=true
majordna.llm.url=https://api.groq.com/openai/v1/chat/completions
majordna.llm.model=openai/gpt-oss-20b
